const content = {
  pages: [
    {
      title: "Whey Protein Isolate",
      description: `
      WPI is the high quality protein, which is typically around 90% protein by weight. 
      It is the purest form of whey protein that currently exists. 
      WPI is more expensive than other proteins or blends of proteins, however if you need pure protein, it is the way to go.`,
      subdescription: `Prices are updated daily`,
      path: "/wpi",
      content:
        "<p>Foo content...</p><h2>Heading</h2><p>Some other content...</p>",
      products: [
        {
          name: "Bulk Nutrients WPI",
          datasourceId: 43,
          link: "https://www.bulknutrients.com.au/products/whey-protein-isolate",
          image:
            "https://www.bulknutrients.com.au/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2F263h0ltd%2Fproduction%2Fab40cd7d16a644d40dadb63e9c7bb4e81b0b59cb-1000x1000.webp%3Fw%3D500%26h%3D500%26q%3D100%26fit%3Dfillmax&w=640&q=100",
          shipsFrom: "Hobart",
          packageSize: 1,
          nutritional: {
            protein: 88.5,
            fats: 1,
            carbs: 2.9,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Banana",
            "Choc Honeycomb",
            "Choc Peanut",
            "Cookies and Cream",
            "Iced Coffee",
            "Raw (unflavoured)",
            "Salted Caramel",
            "Strawberry",
            "Vanilla Maple",
          ],
        },
        {
          name: "AminoZ WPI",
          datasourceId: 45,
          link: "https://www.aminoz.com.au/amino-z-whey-protein-isolate-wpi.html",
          image:
            "https://www.aminoz.com.au/media/catalog/product/cache/1/thumbnail/460x440/9df78eab33525d08d6e5fb8d27136e95/w/p/wpi_choc_orange.jpg",
          shipsFrom: "Hobart",
          packageSize: 1,
          nutritional: {
            protein: 79.7,
            fats: 2.3,
            carbs: 5.5,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Banana",
            "Choc Orange",
            "Choc Peanut",
            "Cookies and Cream",
            "Iced Coffee",
            "Raw (unflavoured)",
            "Strawberry",
            "Vanilla Maple",
          ],
        },
        {
          name: "MyProtein WPI",
          datasourceId: 44,
          image:
            "https://static.thcdn.com/images/small/webp//productimg/130/130/12313192-1024850011022415.jpg",
          link: "https://au.myprotein.com/sports-nutrition/impact-whey-isolate/12313192.html",
          shipsFrom: "Melbourne",
          packageSize: 1,
          nutritional: {
            protein: 90,
            fats: 0.3,
            carbs: 2.5,
          },
          flavours: [
            "Apple Crumble",
            "Banana",
            "Blueberry",
            "Blueberry Cheesecake",
            "Cherry Yoghurt",
            "Chocolate & Coconut",
            "Chocolate Banana",
            "Chocolate Brownie",
            "Choc Mint",
            "Choc Orange",
            "Chocolate Peanut Butter",
            "Chocolate Smooth",
            "Chocolate Stevia",
            "Cinnamon Danish",
            "Coffee Caramel",
            "Cookies & Cream",
            "Honeycomb",
            "Mango",
            "Milk Tea",
            "Mocha",
            "Natural Chocolate",
            "Natural Strawberry",
            "Natural Vanilla",
            "Peach Tea",
            "Salted Caramel",
            "Strawberry Cream",
            "Tiramisu",
            "Raw (unflavoured)",
            "Vanilla",
            "Vanilla Raspberry",
            "Vanilla Stevia",
            "White Chocolate",
          ],
        },
        {
          name: "VPA WPI",
          datasourceId: 42,
          image:
            "https://cdn.shopify.com/s/files/1/0268/9279/5959/products/ce94f765-03d2-4a4f-882a-262a88aea680_400x.png?v=1624429080",
          link: "https://www.vpa.com.au/products/whey-isolate-protein-powder",
          shipsFrom: "Brisbane",
          packageSize: 1,
          nutritional: {
            protein: 88.0,
            fats: 0.7,
            carbs: 2.5,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Strawberry",
            "Banana",
            "Raw (unflavoured)",
            "Iced Coffee",
            "Rainbow Ice Cream",
            "Salted Caramel",
            "Choc Banana",
            "Choc Caramel",
            "Coconut",
            "Choc Mint",
            "Rich Mocha",
            "Choc Coconut",
          ],
        },
        {
          name: "UProtein WPI",
          datasourceId: 50,
          image:
            "https://cdn10.bigcommerce.com/s-02hgc0/products/98/images/566/Whey-Isolate-Premium-2kg__21959.1618985567.764.714.jpg?c=2",
          link: "https://www.uprotein.com.au/whey-protein-isolate-protein-powder-online/",
          shipsFrom: "Sydney",
          packageSize: 2,
          nutritional: {
            protein: 91.0,
            fats: 0.5,
            carbs: 0.5,
          },
          flavours: ["Chocolate", "Vanilla", "Raw (unflavoured)"],
        },
        {
          name: "Bulk Powders WPI",
          datasourceId: 51,
          image:
            "https://www.bulkpowders.com.au/media/catalog/product/cache/1/image/320x320/9df78eab33525d08d6e5fb8d27136e95/e/s/essentials_1kg_5.jpg",
          link: "https://www.bulkpowders.com.au/whey-protein-isolate.html",
          shipsFrom: "Melbourne",
          packageSize: 1,
          nutritional: {
            protein: 84.9,
            fats: 1.0,
            carbs: 1.0,
          },
          flavours: [
            "Caramel",
            "Chocolate",
            "Vanilla",
            "Strawberry",
            "Banana",
            "Honeycomb",
          ],
        },
        {
          name: "Bare Blends WPI",
          datasourceId: 47,
          image:
            "https://cdn.shopify.com/s/files/1/0437/5160/4387/products/BI.jpg?v=1662526155",
          link: "https://bareblends.com.au/bare-whey-protein-isolate?size=750g",
          shipsFrom: "Melbourne",
          packageSize: 0.75,
          nutritional: {
            protein: 87.3,
            fats: 1.0,
            carbs: 1.4,
          },
          flavours: ["Chocolate", "Vanilla", "Raw (unflavoured)"],
        },
        {
          name: "Professional Whey WPI",
          datasourceId: 59,
          image:
            "https://www.professionalwhey.com.au/assets/thumbL/P1_PW_WPI_USA.png?20220528063251",
          link: "https://www.professionalwhey.com.au/usa-whey-protein-isolate",
          shipsFrom: "Sydney",
          packageSize: 1,
          nutritional: {
            protein: 86,
            fats: 1.1,
            carbs: 3.3,
          },
          flavours: ["Chocolate", "Vanilla", "Raw (unflavoured)"],
        },
        {
          name: "Nutrition Warehouse: Optimum Nutrition WPI",
          datasourceId: 49,
          image:
            "https://cdn.shopify.com/s/files/1/0613/6342/1411/products/optimum-nutrition-gold-standard-wy-1lb-vanilla-icecream_5f0034ca-0451-4e34-ae6e-9df830d0c23f_600x600.jpg?v=1670292097",
          link: "https://www.nutritionwarehouse.com.au/products/gold-standard-100-isolate-by-optimum-nutrition",
          shipsFrom: "Sydney",
          packageSize: 0.74,
          nutritional: {
            protein: 81,
            fats: 2,
            carbs: 3,
            kilojoules: 1462,
          },
          flavours: ["Chocolate", "Vanilla"],
        },
      ],
    },
    {
      title: "Whey Protein Concentrate",
      description:
        "WPC is a less processed form of whey protein and contains less protein by weight than WPI. It is the most common and affordable form of whey protein.",
      subdescription: `Prices are updated daily`,
      path: "/wpc",
      content: "<p><strong>Bar</strong> content...</p>",
      products: [
        {
          name: "Bulk Nutrients WPC",
          datasourceId: 54,
          link: "https://www.bulknutrients.com.au/products/whey-protein-concentrate",
          image:
            "https://www.bulknutrients.com.au/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2F263h0ltd%2Fproduction%2Ff67727a780c95edcad7d6b43e9cde6eaa6d5002f-1000x1000.webp%3Fw%3D500%26h%3D500%26q%3D100%26fit%3Dfillmax&w=640&q=100",
          shipsFrom: "Hobart",
          packageSize: 1,
          nutritional: {
            protein: 77.1,
            fats: 5.9,
            carbs: 8.6,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Banana",
            "Choc Honeycomb",
            "Choc Peanut",
            "Cookies and Cream",
            "Iced Coffee",
            "Raw (unflavoured)",
            "Salted Caramel",
            "Strawberry",
            "Vanilla Maple",
          ],
        },
        {
          name: "AminoZ WPC",
          datasourceId: 46,
          link: "https://www.aminoz.com.au/amino-z-whey-protein-concentrate-wpc.html",
          image:
            "https://www.aminoz.com.au/media/catalog/product/cache/1/thumbnail/460x440/9df78eab33525d08d6e5fb8d27136e95/w/p/wpc_chocolate.jpg",
          shipsFrom: "Sydney",
          packageSize: 1,
          nutritional: {
            protein: 71.1,
            fats: 6.6,
            carbs: 10.5,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Banana",
            "Choc Coconut",
            "Iced Coffee",
            "Raw (unflavoured)",
            "Strawberry",
          ],
        },
        {
          name: "UProtein WPC",
          datasourceId: 57,
          link: "https://www.uprotein.com.au/100-whey-protein-powder-enzymes-2kgs/",
          image:
            "https://cdn10.bigcommerce.com/s-02hgc0/products/96/images/572/100-Whey-Hydro-2kg__69332.1618990104.764.714.jpg?c=2",
          shipsFrom: "Sydney",
          packageSize: 2,
          nutritional: {
            protein: 81.4,
            fats: 3.8,
            carbs: 5.5,
          },
          flavours: ["Chocolate", "Vanilla", "Banana"],
        },
        {
          name: "MyProtein WPC",
          datasourceId: 55,
          image:
            "https://static.thcdn.com/images/xsmall/webp//productimg/original/12313192-1024850011022415.jpg",
          link: "https://au.myprotein.com/sports-nutrition/impact-whey-protein/12506109.html",
          shipsFrom: "Melbourne",
          packageSize: 1,
          nutritional: {
            protein: 82,
            fats: 7.5,
            carbs: 4,
          },
          flavours: [
            "Apple Crumble",
            "Banana",
            "Blueberry",
            "Blueberry Cheesecake",
            "Cherry Yoghurt",
            "Chocolate & Coconut",
            "Chocolate Banana",
            "Chocolate Brownie",
            "Choc Mint",
            "Choc Orange",
            "Chocolate Peanut Butter",
            "Chocolate Smooth",
            "Chocolate Stevia",
            "Cinnamon Danish",
            "Coffee Caramel",
            "Cookies & Cream",
            "Honeycomb",
            "Mango",
            "Milk Tea",
            "Mocha",
            "Natural Chocolate",
            "Natural Strawberry",
            "Natural Vanilla",
            "Peach Tea",
            "Salted Caramel",
            "Strawberry Cream",
            "Tiramisu",
            "Raw (unflavoured)",
            "Vanilla",
            "Vanilla Raspberry",
            "Vanilla Stevia",
            "White Chocolate",
          ],
        },
        {
          name: "Bulk Powders WPC",
          datasourceId: 52,
          link: "https://www.bulkpowders.com.au/whey-protein-concentrate.html",
          image:
            "https://www.bulkpowders.com.au/media/catalog/product/cache/1/image/320x320/9df78eab33525d08d6e5fb8d27136e95/e/s/essentials_1kg_4.jpg",
          shipsFrom: "Melbourne",
          packageSize: 1,
          nutritional: {
            protein: 74.5,
            fats: 7.4,
            carbs: 6.4,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Banana",
            "Caramel",
            "Honeycomb",
            "Raw (unflavoured)",
            "Strawberry",
          ],
        },
        {
          name: "VPA WPC",
          datasourceId: 53,
          image:
            "https://cdn.shopify.com/s/files/1/0268/9279/5959/products/c2796e71-aa14-4577-87d3-31d97e04c11f_400x.png?v=1624429081",
          link: "https://www.vpa.com.au/collections/protein-powder/products/premium-whey-wpc",
          shipsFrom: "Brisbane",
          packageSize: 1,
          nutritional: {
            protein: 79.0,
            fats: 5.8,
            carbs: 8.3,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Strawberry",
            "Banana",
            "Raw (unflavoured)",
            "Iced Coffee",
            "Rainbow Ice Cream",
            "Salted Caramel",
            "Choc Banana",
            "Choc Caramel",
            "Coconut",
            "Choc Mint",
            "Rich Mocha",
            "Choc Coconut",
          ],
        },
        {
          name: "Bare Blends WPC",
          datasourceId: 56,
          image:
            "https://cdn.shopify.com/s/files/1/0437/5160/4387/products/VC.jpg?v=1662526449",
          link: "https://bareblends.com.au/vanilla-bean-whey-protein-concentrate",
          shipsFrom: "Melbourne",
          packageSize: 0.75,
          nutritional: {
            protein: 78.5,
            fats: 7.1,
            carbs: 6.2,
          },
          flavours: ["Chocolate", "Vanilla", "Raw (unflavoured)"],
        },
        {
          name: "Professional Whey WPC",
          datasourceId: 58,
          image:
            "https://www.professionalwhey.com.au/assets/thumbL/PW_WPC_NAT_1KG.jpg?20210527194304",
          link: "https://www.professionalwhey.com.au/aus-whey-protein-concentrate",
          shipsFrom: "Sydney",
          packageSize: 1,
          nutritional: {
            protein: 75.2,
            fats: 6.5,
            carbs: 10.1,
          },
          flavours: [
            "Chocolate",
            "Vanilla",
            "Raw (unflavoured)",
            "Banana",
            "Salted Caramel",
          ],
        },
        {
          name: "Nutrition Warehouse: Optimum Nutrition WPC",
          datasourceId: 49,
          image:
            "https://cdn.shopify.com/s/files/1/0613/6342/1411/products/optimum-nutrition-gold-standard-wy-1lb-vanilla-icecream_5f0034ca-0451-4e34-ae6e-9df830d0c23f_600x600.jpg?v=1670292097",
          link: "https://www.nutritionwarehouse.com.au/products/gold-standard-100-whey-by-optimum-nutrition",
          shipsFrom: "Sydney",
          packageSize: 0.45,
          nutritional: {
            protein: 77.4,
            fats: 4.8,
            carbs: 12.9,
            kilojoules: 1713,
          },
          flavours: ["Chocolate", "Vanilla"],
        },
      ],
    },
    {
      title: "Mass Gainer",
      description:
        "Mass Gainer is a high protein, high carbohydrate supplement designed to help you gain weight and muscle mass. It is usually consumed by people who have a hard time gaining weight and muscle mass.",
      subdescription:
        "Yeah, yeah I'm getting there. Wanting to add mass gainers to the site... Any suggestions drop me a line.",
      path: "/mass-gainer",
      content: "<p><strong>Bar</strong> content...</p>",
      products: [],
    },
  ],
};

export default content;
